### ISSUE TITLE
Error executing command

### ISSUE THREAD

**Issue by r4phl** [hardwaterhacker/CrazyParser#5]
root@mdm:~/CrazyParser# ./crazyParser.py --urlcrazy
Traceback (most recent call last):
  File "./crazyParser.py", line 354, in <module>
    main()
  File "./crazyParser.py", line 345, in main
    parseOutput(docRoot, knownDomains, resultsFile, args.urlcrazy, args.dnstwist)
  File "./crazyParser.py", line 171, in parseOutput
    if row['CC-A'] != "?":
KeyError: 'CC-A'

root@mdm:~/CrazyParser# ./crazyParser.py --dnstwist
Traceback (most recent call last):
  File "./crazyParser.py", line 354, in <module>
    main()
  File "./crazyParser.py", line 345, in main
    parseOutput(docRoot, knownDomains, resultsFile, args.urlcrazy, args.dnstwist)
  File "./crazyParser.py", line 186, in parseOutput
    if row[1] in knowndom:
IndexError: list index out of range
root@mdm:~/CrazyParser#

**Comment by fenderstrato666** [comment]
Did you get the chance to solve this ?
